<a href="https://colab.research.google.com/github/Mayank224472/Mayank_Yadav/blob/WhiteHat_Mayank_Applied_Tech/Whitehat_Mayank_Lesson_31.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 31: Python Dictionary Operations I



In [ ]:
a=1
b=2
print(a)
b

1


2

### Teacher-Student Activities

Let's take forward our discussion on Python dictionaries. In this class, we will learn to retrieve items from Python dictionaries. We will first learn to find the number of items stored in a dictionary, then how to retrieve only keys, then only values and then how to retrieve both of them together as a pair.

Let's quickly create the `my_dict` dictionary again and continue this class from the **Activity 1: Dictionary Length** section.

---

#### Recap

**A python dictionary is a collection of key-value pairs.** 

|Key         |Value                  |
|------------|-----------------------|
|Front Camera|16 MP                  |
|Battery     |3300 mAh               |
|Processor   |Qualcomm Snapdragon 845|
|Display     |6.28 inches            |
|RAM         |6 GB                   |
|Rear Camera |16 MP + 20 MP          |
|Price (INR) |28990                  |
|Fast Charge |True                   |

Collectively, both a key and its corresponding value constitute an item stored in a dictionary. 

A dictionary is created using curly brackets (`{}`). A key and its corresponding value are mapped using the colon (`:`) sign and each key-value pair is separated by a comma. 

In [ ]:
# Create a dictionary as a collection of key-value pairs containing the items shown in the table above.
my_dict = {'Front Camera' : '16 MP', # First key-value pair 
           'Battery' : '3300 mAh', # Second key-value pair
           'Processor' : 'Qualcomm Snapdragon 845', # Third key-value pair
           'Display' : '6.28 inches', # Fourth key-value pair
           'RAM' : '6 GB', # Fifth key-value pair
           'Rear Camera' : '16 MP + 20 MP', # Sixth key-value pair
           'Price' : 28990, # Seventh key-value pair
           'Fast Charge' : True} # Eighth key-value pair

my_dict

{'Battery': '3300 mAh',
 'Display': '6.28 inches',
 'Fast Charge': True,
 'Front Camera': '16 MP',
 'Price': 28990,
 'Processor': 'Qualcomm Snapdragon 845',
 'RAM': '6 GB',
 'Rear Camera': '16 MP + 20 MP'}

**Note** that the output will not always display the key-value pairs in the same order in which you entered the pairs in the dictionary.

---

#### Activity 1: Dictionary Length
The length of a dictionary or dictionary length is the number of key-value pairs contained in the dictionary. The `my_dict` has eight key-value pairs. So, the length of `my_dict` is 8.

To calculate the length of a dictionary (or number of key-value pairs contained in a dictionary), you can use the `len()`  function.

In [ ]:
# Student Action: Calculate the length of the 'my_dict' dictionary.
len(my_dict)

8

As you can see, the `len()` function when applied on `my_dict` returns a numeric value `8` signifying that the dictionary stored in the `my_dict` variable has `8` key-value pairs.

---

#### Activity 2: The `keys()` Function
To get a list of all the keys in a dictionary, you can use the `keys()` function using the `dictionary_name.keys()` method.

Refer to the code shown below.

In [ ]:
# Student Action: Get the list of all the keys contained in 'my_dict' dictionary.
my_dict.keys()

dict_keys(['Front Camera', 'Battery', 'Processor', 'Display', 'RAM', 'Rear Camera', 'Price', 'Fast Charge'])

As you can see, the `keys()` function has returned a list of all the keys contained in the `my_dict` dictionary.

**Note** that the list returned by the `keys()` function is not the same as a Python list. It behaves differently as compared to a conventional Python list. 

You can also use a `for` loop to print all the keys of a dictionary one after the other.


In [ ]:
# Student Action: Get the list of all the keys contained in 'my_dict' dictionary using 'for' loop.
for i in my_dict.keys():
  print(i)
  



Front Camera
Battery
Processor
Display
RAM
Rear Camera
Price
Fast Charge


Actually, even if you don't use the `keys()` function, you can retrieve all the keys from a Python dictionary using a `for` loop. Let's retrieve all the keys from the `my_dict` dictionary without using the `keys()` function.

In [ ]:
# Student Action: Retrieve all the keys present in 'my_dict' dictionary without using the 'keys()' function but using 'for' loop.
for i in my_dict: 
  print(i)

Front Camera
Battery
Processor
Display
RAM
Rear Camera
Price
Fast Charge


---

#### Activity 3: Getting A Value For A Key^

Now let's learn how to retrieve a value for a key from a Python dictionary. There are two methods to do this. They are:

1. The square brackets method

2. The `get()` function


**Method I: The Square Brackets**

For a key, in a dictionary, you can retrieve its corresponding value by using the `dictionary_name[key]` method where `dictionary_name` is the variable storing a Python dictionary and `key` is the key stored in the dictionary.


In [ ]:
# Student Action: Print the corresponding values to each key contained in the 'my_dict' dictionary.
# Value for the first key.
print(my_dict['Front Camera'])
# Value for the second key.
print(my_dict['Battery'])
# Value for the third key.
print(my_dict['Processor'])
# Value for the fourth key.
print(my_dict['Display'])
# Value for the fifth key.
print(my_dict['RAM'])
# Value for the sixth key.
print(my_dict['Rear Camera'])
# Value for the seventh key.
print(my_dict['Price'])
# Value for the eighth key.
my_dict['Fast Charge']

16 MP
3300 mAh
Qualcomm Snapdragon 845
6.28 inches
6 GB
16 MP + 20 MP
28990


True

Instead of retrieving all the values one-by-one, you can get them using a `for` loop along with keys enclosed in square brackets.

In [ ]:
# Student Action: Print all the values contained in the 'my_dict' dictionary using a 'for' loop, 'keys()' function & square brackets. 
for i in my_dict:
  print(my_dict[i])

16 MP
3300 mAh
Qualcomm Snapdragon 845
6.28 inches
6 GB
16 MP + 20 MP
28990
True


The `my_dict.keys()` code returns a list of all the keys in a dictionary. In this case the list of keys is 

`dict_keys(['Front Camera', 'Battery', 'Processor', 'Display', 'RAM', 'Rear Camera', 'Price', 'Fast Charge'])`

- Next, `for` loop iterates through each key in the above list and stores them in the `key` variable one-by-one. 

- Then, `my_dict[key]` returns a value for the key stored in the `key` variable.

- Finally, the `print()` function prints the value for each `key`, as you can see in the output.

You don't necessarily have to use the `keys()` function to retrieve all the values from a dictionary.

In [ ]:
# Student Action: Print all the values stored in the 'my_dict' dictionary using 'for' loop & the square brackets.
for i in my_dict.keys():
  print(my_dict[i])

16 MP
3300 mAh
Qualcomm Snapdragon 845
6.28 inches
6 GB
16 MP + 20 MP
28990
True


**Note:** In a way, the keys act like indices for a Python dictionary. Unlike a Python list, a Python dictionary does not have indices of their own because a dictionary is an **unordered** collection of items. An only ordered collection of items have indices. Also, since a Python dictionary does not have indices, it is best to use `for` loop over `while` loop to iterate through each item that is stored in a dictionary.

**Method II: The `get()` Function**

You can also use the `get()` function to get a value of a key by using the `dictionary_name.get(key)` method.


In [ ]:
# Student Action: Print the corresponding values to each key contained in the 'my_dict' dictionary using the 'get()' function.
# Value for the first key.
print(my_dict.get('Front Camera'))
# Value for the second key.
print(my_dict.get('Battery'))
# Value for the third key.
print(my_dict.get('Processor'))
# Value for the fourth key.
print(my_dict.get('Display'))
# Value for the fifth key.
print(my_dict.get('RAM'))
# Value for the sixth key.

# Value for the seventh key.

# Value for the eighth key.


16 MP
3300 mAh
Qualcomm Snapdragon 845
6.28 inches
6 GB


Similarly, you can also use the `get()` function with `for` loop to get the value for a key. 

In [ ]:
# Student Action: Print all the values contained in the 'my_dict' dictionary using 'for' loop and the 'get()' function. 
for i in my_dict:
  print(my_dict.get(i))

16 MP
3300 mAh
Qualcomm Snapdragon 845
6.28 inches
6 GB
16 MP + 20 MP
28990
True


In the code above, `for` loop iterates through each key in the list generated by the `keys()` function. Then, the `get()` function returns the value for a key. Finally, the `print()` function prints the corresponding value for each key.

---

#### Activity 4: The `values()` Function^^

Let's learn how to get the collection of all the values contained in a Python dictionary. You can do this by using the `values()` function. 

**Syntax:** `dictionary_name.values()`


In [ ]:
# Student Action: Retrieve a collection of all the values stored in the 'my_dict' dictionary using the 'values()' function.
my_dict.values()

dict_values(['16 MP', '3300 mAh', 'Qualcomm Snapdragon 845', '6.28 inches', '6 GB', '16 MP + 20 MP', 28990, True])

As you can see, the `values()` function has returned a list of all the values contained in the `my_dict` dictionary.

**Note** that the list returned by the `values()` function is not the same as a Python list. This list behaves differently as compared to a conventional Python list. 

You can also use a `for` loop to print each item contained in the list returned by the `values()` function.

In [ ]:
# Student Action: Using 'for' loop, print each item contained in the list returned by the 'values()' function.
for i in my_dict.values():
  print(i)

16 MP
3300 mAh
Qualcomm Snapdragon 845
6.28 inches
6 GB
16 MP + 20 MP
28990
True


As you can see, in the `for` loop, the `value` variable iterates through every value contained in the list, 

`dict_values(['16 MP', '3300 mAh', 'Qualcomm Snapdragon 845', '6.28 inches', '6 GB', '16 MP + 20 MP', 28990, True])`

Then, the `print()` function prints the value stored in the `value` variable.

---

#### Activity 5: The `items()` Function^^^

You can also retrieve all the key-value pairs from a dictionary as a collection of tuples by using the `items()` function.

**Syntax:** `dictionary_name.items()` method.


In [ ]:
# Student Action: Retrieve all the items stored in the 'my_dict' dictionary as a collection of tuples.
my_dict.items()

dict_items([('Front Camera', '16 MP'), ('Battery', '3300 mAh'), ('Processor', 'Qualcomm Snapdragon 845'), ('Display', '6.28 inches'), ('RAM', '6 GB'), ('Rear Camera', '16 MP + 20 MP'), ('Price', 28990), ('Fast Charge', True)])

As you can see, the `items()` function has returned a list of key-value pairs contained in the `my_dict` dictionary. Each key-value pair is a tuple because a pair is written inside the common brackets, i.e., `()`. 

**Note** that the list returned by the `items()` function is not the same as a Python list. This list behaves differently as compared to a conventional Python list. 

You can also use a `for` loop to print each item contained in the list returned by the `items()` function. 


In [ ]:
# Student Action: Loop through each item stored in the list returned by the 'items()' function.
for i in my_dict.items():
  print(i)

('Front Camera', '16 MP')
('Battery', '3300 mAh')
('Processor', 'Qualcomm Snapdragon 845')
('Display', '6.28 inches')
('RAM', '6 GB')
('Rear Camera', '16 MP + 20 MP')
('Price', 28990)
('Fast Charge', True)


As you can see, using `for` loop, we have retrieved every tuple containing a key-value pair, from the `my_dict` dictionary.

You can also simultaneously iterate through each key-value contained in the list returned by the `items()` function. 

In [ ]:
# Student Action: Simultaneously iterate through each key-value pair contained in the list returned by the 'items()' function.
for i,j in my_dict.items():
  print(i,j)

Front Camera 16 MP
Battery 3300 mAh
Processor Qualcomm Snapdragon 845
Display 6.28 inches
RAM 6 GB
Rear Camera 16 MP + 20 MP
Price 28990
Fast Charge True


As you can see, in the `for` loop, the `key` variable iterates through each key in each item and the `value` variable iterates through each value in each item contained in the list, 

`dict_items([('Front Camera', '16 MP'), ('Battery', '3300 mAh'), ('Processor', 'Qualcomm Snapdragon 845'), ('Display', '6.28 inches'), ('RAM', '6 GB'), ('Rear Camera', '16 MP + 20 MP'), ('Price', 28990), ('Fast Charge', True)])`

Then, the `print()` function prints the values stored in the `key` and `value` variables.

If you apply the same method of retrieving key-value pairs simultaneously directly from the `my_dict` dictionary, then you will get `ValueError`.

In [ ]:
# Student Action: Simultaneously retrieve all the key-value pairs directly from the 'my_dict' dictionary.
for i,j in my_dict.keys():
  print(i,j)

ValueError: ignored

Hence, to simultaneously iterate through multiple items (or key-value pairs), it is best to have each item (or key-value pair) as a collection of tuples. You will learn about tuples in detail in the upcoming classes.

Let's take a pause here and continue the discussion on Python dictionaries in the next lesson.


---